package entity.common;
// Generated 19/03/2013 2:31:28 AM by Hibernate Tools 3.2.1.GA

/**
 * Employee generated by hbm2java
 */
public class Employee extends Person {

    private int employeeId;
    private int department;
    private boolean status;

    public Employee() {
    }

    public int getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    public int getDepartment() {
        return this.department;
    }

    public void setDepartment(int department) {
        this.department = department;
    }

    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }
}
