package entity.common;
// Generated 19/03/2013 2:31:28 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserAuth generated by hbm2java
 */
public class UserAuth  implements java.io.Serializable {


     private int employeeId;
     private String username;
     private String password;
     private Date lastLogin;
     private boolean status;

    public UserAuth() {
    }

    public UserAuth(int employeeId, String username, String password, Date lastLogin, boolean status) {
       this.employeeId = employeeId;
       this.username = username;
       this.password = password;
       this.lastLogin = lastLogin;
       this.status = status;
    }
   
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


